import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/src/styles/Home.module.css'
import Signup from '../components/signup'
import { Provider } from 'react-redux'
import store from '../redux/store'
import MainScreen from '../components/mainScreen'




export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Codeleap</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Provider store={store}>
        <main className={styles.main}>
          <Signup />
          {/* <MainScreen posts={posts} /> */}
        </main >
      </Provider>
    </>
  )
}


