"use client"
import '@/src/styles/globals.css';
import { Provider } from 'react-redux';
import store from '../redux/store';
import Head from './head';
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head />
      <Provider store={store}>
        <body>{children}</body>
      </Provider>
    </html>
  )
}
